### ISSUE TITLE
No validation and Error popup while giving wrong info 

### ISSUE THREAD

**Issue by rajathjn** [pes-alcoding-club/alcoding-web-portal#101]
![screenshot 19 _li](https://user-images.githubusercontent.com/28223601/50006154-d1085780-ffd2-11e8-9d9b-2bcb91006389.jpg)

Raising this issue to the above cited, 
As you can see there is no error pop up when the year entered is very much greater than the present year!!
also it would be a great help if the website is able to identify whether the entered email is valid or invalid.

**Comment by aniketnk** [comment]
Yes, this is a known issues. Would be great if you could help us fix it. Open a PR and we'll review it!

**Comment by aniketnk** [comment]
Even the phone number could be validated using some Regex.

**Comment by emperorjnx** [comment]
Already working on it.
Thanks i will look into that

**Comment by souravtecken** [comment]
I think this has been adrressed in #111
